### PR TITLE
Class components are being replaced with functional components and hooks

### PR DESCRIPTION
**Pull request by swarup4741**
Replaced all the class components with functional components and hooks. Also you may find some cosmetics change and the lock-file as well in the PR

### CODE REVIEW

**Review by LachPawel — COMMENTED** [review]
So far everything looks good to me! :) There is no need to import React anymore. Additionally, I can create a legacy branch before merging.

**Review by swarup4741 — COMMENTED** [review]
So do i need to Remove `import React` ... after that you will merge ?

**Comment by KowalewskiPawel** [comment]
> So do i need to Remove `import React` ... after that you will merge ?

As you wish, it can be more readable. Let me create a new branch in order not to lose the class component version for the tutorial legacy purposes. I am a bit busy with something currently, but will try to solve the problem and merge asap. ;)

**Review by LachPawel — APPROVED** [review]

**Comment by KowalewskiPawel** [comment]
Changes added to the main branch, old version can be found on the "legacy" branch.

**Pull request merged**
